/**
 * The UPPER_SNAKE codes in `error.code` (spec 0.4).
 *
 * This is the only thing the client branches on, so every value here is stable
 * forever once shipped. Reword the message freely; never rename a code.
 */
export const ApiErrorCode = {
  // ─── Generic ───────────────────────────────────────────────────────────────
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  /**
   * A deleted post returns 404 with this rather than disappearing from a list
   * silently, so the client can render a tombstone where the user tapped (0.4).
   */
  RESOURCE_DELETED: 'RESOURCE_DELETED',

  // ─── Account deletion (0.15) ───────────────────────────────────────────────
  ACCOUNT_ALREADY_DELETED: 'ACCOUNT_ALREADY_DELETED',
  INVALID_CODE: 'INVALID_CODE',

  // ─── Media (0.11) ──────────────────────────────────────────────────────────
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_ALREADY_ATTACHED: 'MEDIA_ALREADY_ATTACHED',
  MEDIA_TYPE_NOT_ALLOWED: 'MEDIA_TYPE_NOT_ALLOWED',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_MIXED_TYPES: 'MEDIA_MIXED_TYPES',
  MEDIA_LIMIT_EXCEEDED: 'MEDIA_LIMIT_EXCEEDED',

  // ─── Taxonomy ──────────────────────────────────────────────────────────────
  UNKNOWN_TAXONOMY_CODE: 'UNKNOWN_TAXONOMY_CODE',
  UNKNOWN_CITY: 'UNKNOWN_CITY',

  // ─── Section 1: Community ──────────────────────────────────────────────────
  USE_PRIVATE_ENDPOINT: 'USE_PRIVATE_ENDPOINT',
  REQUEST_NOT_EDITABLE: 'REQUEST_NOT_EDITABLE',
  REQUEST_ALREADY_RESOLVED: 'REQUEST_ALREADY_RESOLVED',
  REQUEST_CLOSED: 'REQUEST_CLOSED',
  NOT_A_RESPONDER: 'NOT_A_RESPONDER',
  ALREADY_OFFERED: 'ALREADY_OFFERED',
  CANNOT_OFFER_ON_OWN_REQUEST: 'CANNOT_OFFER_ON_OWN_REQUEST',
  COMMENTS_DISABLED: 'COMMENTS_DISABLED',
  GROUP_NAME_TAKEN: 'GROUP_NAME_TAKEN',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  LAST_ADMIN_CANNOT_LEAVE: 'LAST_ADMIN_CANNOT_LEAVE',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  GUIDE_PROVENANCE_REQUIRED: 'GUIDE_PROVENANCE_REQUIRED',

  // ─── Section 2: Professionals ──────────────────────────────────────────────
  LISTING_ALREADY_EXISTS: 'LISTING_ALREADY_EXISTS',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  OFFER_ALREADY_PROMOTED: 'OFFER_ALREADY_PROMOTED',
  NOT_ACCEPTING_WORK: 'NOT_ACCEPTING_WORK',
  SERVICE_INACTIVE: 'SERVICE_INACTIVE',
  CANNOT_BOOK_YOURSELF: 'CANNOT_BOOK_YOURSELF',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  VERIFICATION_INCOMPLETE: 'VERIFICATION_INCOMPLETE',
  DISPUTE_ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',
  NOT_A_PROFESSIONAL: 'NOT_A_PROFESSIONAL',
  REVIEW_ALREADY_LEFT: 'REVIEW_ALREADY_LEFT',
  REVIEW_NOT_ELIGIBLE: 'REVIEW_NOT_ELIGIBLE',
  REVIEW_FROZEN: 'REVIEW_FROZEN',
  CANNOT_REVIEW_YOURSELF: 'CANNOT_REVIEW_YOURSELF',

  // ─── Section 3: Connect ────────────────────────────────────────────────────
  CONNECT_PROFILE_REQUIRED: 'CONNECT_PROFILE_REQUIRED',
  UNDER_MINIMUM_AGE: 'UNDER_MINIMUM_AGE',
  DOB_LOCKED: 'DOB_LOCKED',
  DOB_REQUIRED: 'DOB_REQUIRED',
  DATING_CONFIRMATION_REQUIRED: 'DATING_CONFIRMATION_REQUIRED',
  REQUEST_ALREADY_EXISTS: 'REQUEST_ALREADY_EXISTS',
  DIRECT_MESSAGE_ALLOWED: 'DIRECT_MESSAGE_ALLOWED',
  REQUEST_COOLDOWN: 'REQUEST_COOLDOWN',
  CANNOT_CONNECT_WITH_YOURSELF: 'CANNOT_CONNECT_WITH_YOURSELF',

  // ─── Section 4: Commerce ───────────────────────────────────────────────────
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_CLOSED: 'STORE_CLOSED',
  ITEMS_UNAVAILABLE: 'ITEMS_UNAVAILABLE',
  DELIVERY_NOT_OFFERED: 'DELIVERY_NOT_OFFERED',
  CANNOT_ENQUIRE_OWN_STORE: 'CANNOT_ENQUIRE_OWN_STORE',
  NOT_A_SELLER: 'NOT_A_SELLER',

  // ─── Section 5: Messaging ──────────────────────────────────────────────────
  CONVERSATION_BLOCKED: 'CONVERSATION_BLOCKED',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  MESSAGE_DELETE_WINDOW_PASSED: 'MESSAGE_DELETE_WINDOW_PASSED',
  CANNOT_MESSAGE_YOURSELF: 'CANNOT_MESSAGE_YOURSELF',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
