import { Injectable } from '@nestjs/common';
import {
  ActivitySubject,
  ActivityVerb,
  DeflectionOutcome,
  Guide,
  GuideBlockType,
  Prisma,
  TaxonomyKind,
} from '@prisma/client';
import { PrismaService } from '@/infrastructure';
import {
  ApiErrorCode,
  ApiException,
  buildPageMeta,
  daysAgo,
  Paginated,
  readTimeMinutes,
  toJson,
} from '@/common';
import {
  ActivityService,
  AuthorView,
  CityService,
  CityView,
  MediaService,
  MediaView,
  TaxonomyService,
  TermView,
  authorSelect,
  toAuthorView,
  toCityView,
  toMediaViews,
  toTermView,
} from '../../shared';
import {
  CreateGuideDto,
  GuideFeedbackDto,
  GuideProgressDto,
  ListGuidesDto,
} from '../dtos/guide.dto';

export const GUIDE_MEDIA_OWNER = 'GUIDE';

export interface GuideBlock {
  type: GuideBlockType;
  text: string;
}

export interface GuideSummaryView {
  type: 'GUIDE';
  id: string;
  title: string;
  topic: TermView | null;
  intro: string;
  city: CityView | null;
  readTimeMinutes: number;
  counts: { views: number; likes: number };
  author: AuthorView;
  isAutoGenerated: boolean;
  viewer: { isBookmarked: boolean; hasLiked: boolean; readProgress: number };
  publishedAt: string | null;
}

export interface GuideDetailView extends Omit<GuideSummaryView, 'type'> {
  /** D5: the storage form, for a client that renders blocks. */
  blocks: GuideBlock[];
  /**
   * A projection of the STEP blocks, for the client shipping today. When the
   * client moves to blocks this is dropped from the response and nothing
   * migrates (1.6.2).
   */
  steps: string[];
  resourceUrl: string | null;
  media: MediaView[];
  provenance: {
    summary: string;
    reviewedAt: string | null;
    sources: Array<{ type: string; id: string; label: string }>;
  } | null;
  relatedGuideIds: string[];
}

const guideInclude = {
  author: { select: authorSelect },
  city: { select: { id: true, name: true, region: true } },
} satisfies Prisma.GuideInclude;

type GuideRow = Prisma.GuideGetPayload<{ include: typeof guideInclude }>;

@Injectable()
export class GuideService {
  constructor(
    private readonly database: PrismaService,
    private readonly taxonomy: TaxonomyService,
    private readonly cities: CityService,
    private readonly media: MediaService,
    private readonly activity: ActivityService,
  ) {}

  // ─── 1.6.1 List ────────────────────────────────────────────────────────────

  async list(viewerId: string, query: ListGuidesDto): Promise<Paginated<GuideSummaryView>> {
    const where: Prisma.GuideWhereInput = { deletedAt: null, publishedAt: { not: null } };

    if (query.topic) {
      where.topicCode = query.topic;
    }

    if (query.cityId) where.cityId = query.cityId;

    if (query.q) {
      where.OR = [
        { title: { contains: query.q, mode: Prisma.QueryMode.insensitive } },
        { intro: { contains: query.q, mode: Prisma.QueryMode.insensitive } },
      ];
    }

    let orderBy: Prisma.GuideOrderByWithRelationInput[] = [{ publishedAt: 'desc' }];

    if (query.section === 'CONTINUE_READING') {
      // Guides this member started and did not finish. 0.95 rather than 1.0
      // because a reader who scrolled to the last paragraph has finished it, and
      // offering to resume there is noise.
      const started = await this.database.guideProgress.findMany({
        where: { userId: viewerId, progress: { gt: 0, lt: 0.95 } },
        orderBy: { updatedAt: 'desc' },
        select: { guideId: true },
        take: 50,
      });

      if (!started.length) {
        return { data: [], meta: buildPageMeta(query, 0) };
      }

      where.id = { in: started.map(row => row.guideId) };
    } else if (query.section === 'MOST_READ_THIS_WEEK') {
      where.publishedAt = { not: null, gte: daysAgo(30) };
      orderBy = [{ viewCount: 'desc' }, { publishedAt: 'desc' }];
    } else if (query.sort === 'MOST_READ') {
      orderBy = [{ viewCount: 'desc' }, { publishedAt: 'desc' }];
    } else if (query.sort === 'MOST_LIKED') {
      orderBy = [{ likeCount: 'desc' }, { publishedAt: 'desc' }];
    }

    const [total, rows] = await this.database.$transaction([
      this.database.guide.count({ where }),
      this.database.guide.findMany({
        where,
        include: guideInclude,
        orderBy,
        skip: query.skip,
        take: query.take,
      }),
    ]);

    const context = await this.viewerContext(
      viewerId,
      rows.map(row => row.id),
    );
    const topics = await this.taxonomy.labels(TaxonomyKind.GUIDE_TOPIC);

    return {
      data: rows.map(row => this.toSummary(row, topics, context)),
      meta: buildPageMeta(query, total),
    };
  }

  // ─── 1.6.2 Detail ──────────────────────────────────────────────────────────

  async findOne(viewerId: string, id: string): Promise<GuideDetailView> {
    const guide = await this.database.guide.findUnique({
      where: { id },
      include: { ...guideInclude, sources: true },
    });

    if (!guide) throw ApiException.notFound('This guide could not be found.');
    if (guide.deletedAt) throw ApiException.deleted('This guide');

    if (await this.activity.countView('guide', id, viewerId, guide.authorId)) {
      await this.database.guide.update({ where: { id }, data: { viewCount: { increment: 1 } } });
      guide.viewCount += 1;
    }

    this.activity.record({
      userId: viewerId,
      verb: ActivityVerb.VIEW,
      subject: ActivitySubject.GUIDE,
      subjectId: id,
      cityId: guide.cityId,
      code: guide.topicCode,
    });

    const [context, topics, media, related] = await Promise.all([
      this.viewerContext(viewerId, [id]),
      this.taxonomy.labels(TaxonomyKind.GUIDE_TOPIC),
      this.media.forOwners(GUIDE_MEDIA_OWNER, [id]),
      this.relatedGuideIds(guide),
    ]);

    const { type: _feedType, ...summary } = this.toSummary(guide, topics, context);
    const blocks = this.blocksOf(guide);

    return {
      ...summary,
      blocks,
      steps: blocks.filter(block => block.type === GuideBlockType.STEP).map(block => block.text),
      resourceUrl: guide.resourceUrl,
      media: toMediaViews(media.get(id)),
      provenance: guide.isAutoGenerated
        ? {
            summary: guide.provenanceSummary ?? 'Drafted by Circl from community answers',
            reviewedAt: guide.reviewedAt?.toISOString() ?? null,
            sources: guide.sources.map(source => ({
              type: source.type,
              id: source.refId,
              label: source.label,
            })),
          }
        : null,
      relatedGuideIds: related,
    };
  }

  // ─── 1.6.3 Create ──────────────────────────────────────────────────────────

  async create(userId: string, dto: CreateGuideDto): Promise<GuideDetailView> {
    await this.taxonomy.assertValid(TaxonomyKind.GUIDE_TOPIC, dto.topicCode, 'topicCode');

    if (dto.cityId) await this.cities.assertValid(dto.cityId);

    const steps = dto.steps.map(step => step.trim()).filter(Boolean);

    if (!steps.length) {
      throw ApiException.unprocessable(
        ApiErrorCode.VALIDATION_FAILED,
        'A guide needs at least one step.',
        { details: [{ field: 'steps', message: 'Add at least one step.' }] },
      );
    }

    const blocks: GuideBlock[] = steps.map(text => ({ type: GuideBlockType.STEP, text }));
    const media = await this.media.validate(dto.mediaIds, userId);

    const guide = await this.database.$transaction(async tx => {
      const created = await tx.guide.create({
        data: {
          authorId: userId,
          topicCode: dto.topicCode,
          title: dto.title,
          intro: dto.intro,
          blocks: toJson(blocks),
          resourceUrl: dto.resourceUrl ?? null,
          cityId: dto.cityId ?? null,
          readTimeMinutes: readTimeMinutes([dto.intro, ...steps].join(' ')),
          publishedAt: new Date(),
        },
      });

      await this.media.attach(tx, media, GUIDE_MEDIA_OWNER, created.id);

      return created;
    });

    this.activity.record({
      userId,
      verb: ActivityVerb.CREATE,
      subject: ActivitySubject.GUIDE,
      subjectId: guide.id,
      cityId: guide.cityId,
      code: guide.topicCode,
      term: guide.title,
      weight: 4,
    });

    return this.findOne(userId, guide.id);
  }

  // ─── 1.6.4 Reading state and feedback ──────────────────────────────────────

  async setProgress(
    userId: string,
    id: string,
    dto: GuideProgressDto,
  ): Promise<{ progress: number }> {
    await this.assertExists(id);

    // Progress only ever moves forward. A member who scrolls back up has not
    // un-read the guide, and letting the value drop would drag a finished guide
    // back into the Continue reading strip.
    const existing = await this.database.guideProgress.findUnique({
      where: { guideId_userId: { guideId: id, userId } },
      select: { progress: true },
    });
    const progress = Math.max(existing?.progress ?? 0, dto.progress);

    await this.database.guideProgress.upsert({
      where: { guideId_userId: { guideId: id, userId } },
      update: { progress },
      create: { guideId: id, userId, progress },
    });

    return { progress };
  }

  async setBookmark(
    userId: string,
    id: string,
    bookmarked: boolean,
  ): Promise<{ isBookmarked: boolean }> {
    await this.assertExists(id);

    if (bookmarked) {
      await this.database.guideBookmark.createMany({
        data: [{ guideId: id, userId }],
        skipDuplicates: true,
      });

      this.activity.record({
        userId,
        verb: ActivityVerb.BOOKMARK,
        subject: ActivitySubject.GUIDE,
        subjectId: id,
      });
    } else {
      await this.database.guideBookmark.deleteMany({ where: { guideId: id, userId } });
    }

    return { isBookmarked: bookmarked };
  }

  async react(
    userId: string,
    id: string,
    liked: boolean,
  ): Promise<{ hasLiked: boolean; likeCount: number }> {
    await this.assertExists(id);

    await this.database.$transaction(async tx => {
      if (liked) {
        const result = await tx.guideReaction.createMany({
          data: [{ guideId: id, userId }],
          skipDuplicates: true,
        });

        if (result.count) {
          await tx.guide.update({ where: { id }, data: { likeCount: { increment: 1 } } });
        }
      } else {
        const result = await tx.guideReaction.deleteMany({ where: { guideId: id, userId } });

        if (result.count) {
          await tx.guide.update({ where: { id }, data: { likeCount: { decrement: 1 } } });
        }
      }
    });

    const fresh = await this.database.guide.findUniqueOrThrow({
      where: { id },
      select: { likeCount: true },
    });

    return { hasLiked: liked, likeCount: fresh.likeCount };
  }

  /** One per user per guide, upsert on repeat (1.6.4). */
  async submitFeedback(
    userId: string,
    id: string,
    dto: GuideFeedbackDto,
  ): Promise<{ useful: boolean }> {
    await this.assertExists(id);

    await this.database.guideFeedback.upsert({
      where: { guideId_userId: { guideId: id, userId } },
      update: { useful: dto.useful, note: dto.note ?? null },
      create: { guideId: id, userId, useful: dto.useful, note: dto.note ?? null },
    });

    return { useful: dto.useful };
  }

  /** Fire and forget, so the value of the interstitial is measurable (1.6.5). */
  async recordDeflection(userId: string, id: string, outcome: DeflectionOutcome): Promise<void> {
    await this.database.guideDeflection
      .create({ data: { guideId: id, userId, outcome } })
      .catch(() => undefined);
  }

  // ─── Internals ─────────────────────────────────────────────────────────────

  private blocksOf(guide: Guide): GuideBlock[] {
    return Array.isArray(guide.blocks) ? (guide.blocks as unknown as GuideBlock[]) : [];
  }

  private toSummary(
    row: GuideRow,
    topics: Map<string, string>,
    context: {
      bookmarked: Set<string>;
      liked: Set<string>;
      progress: Map<string, number>;
    },
  ): GuideSummaryView {
    return {
      type: 'GUIDE',
      id: row.id,
      title: row.title,
      topic: toTermView(row.topicCode, topics),
      intro: row.intro,
      city: toCityView(row.city),
      readTimeMinutes: row.readTimeMinutes,
      counts: { views: row.viewCount, likes: row.likeCount },
      author: toAuthorView(row.author),
      isAutoGenerated: row.isAutoGenerated,
      viewer: {
        isBookmarked: context.bookmarked.has(row.id),
        hasLiked: context.liked.has(row.id),
        readProgress: context.progress.get(row.id) ?? 0,
      },
      publishedAt: row.publishedAt?.toISOString() ?? null,
    };
  }

  private async viewerContext(viewerId: string, guideIds: string[]) {
    if (!guideIds.length) {
      return { bookmarked: new Set<string>(), liked: new Set<string>(), progress: new Map() };
    }

    const [bookmarks, reactions, progress] = await Promise.all([
      this.database.guideBookmark.findMany({
        where: { userId: viewerId, guideId: { in: guideIds } },
        select: { guideId: true },
      }),
      this.database.guideReaction.findMany({
        where: { userId: viewerId, guideId: { in: guideIds } },
        select: { guideId: true },
      }),
      this.database.guideProgress.findMany({
        where: { userId: viewerId, guideId: { in: guideIds } },
        select: { guideId: true, progress: true },
      }),
    ]);

    return {
      bookmarked: new Set(bookmarks.map(row => row.guideId)),
      liked: new Set(reactions.map(row => row.guideId)),
      progress: new Map(progress.map(row => [row.guideId, row.progress])),
    };
  }

  /** Same topic, same city first, most read. Cheap, and honest about what it is. */
  private async relatedGuideIds(guide: Guide): Promise<string[]> {
    const rows = await this.database.guide.findMany({
      where: {
        id: { not: guide.id },
        topicCode: guide.topicCode,
        deletedAt: null,
        publishedAt: { not: null },
      },
      orderBy: [{ viewCount: 'desc' }],
      select: { id: true },
      take: 4,
    });

    return rows.map(row => row.id);
  }

  private async assertExists(id: string): Promise<Guide> {
    const guide = await this.database.guide.findUnique({ where: { id } });

    if (!guide) throw ApiException.notFound('This guide could not be found.');
    if (guide.deletedAt) throw ApiException.deleted('This guide');

    return guide;
  }
}
