import { Injectable } from '@nestjs/common';
import { TaxonomyKind } from '@prisma/client';
import { PrismaService } from '@/infrastructure';
import { GuideMatcherService } from '../../intelligence/services/guide-matcher.service';
import {
  MediaService,
  TaxonomyService,
  authorSelect,
  toAuthorView,
  toCityView,
  toTermView,
} from '../../shared';
import { GuideMatchDto } from '../dtos/guide.dto';

/** Turns the matcher's ids into the summary payloads the interstitial renders (1.6.5). */
@Injectable()
export class GuideMatchService {
  constructor(
    private readonly database: PrismaService,
    private readonly matcher: GuideMatcherService,
    private readonly taxonomy: TaxonomyService,
    private readonly media: MediaService,
  ) {}

  async match(dto: GuideMatchDto) {
    const result = await this.matcher.match(dto);

    if (!result.matches.length) {
      return { matches: [], similarAskCount: result.similarAskCount };
    }

    const guideIds = result.matches.filter(m => m.type === 'GUIDE').map(m => m.id);
    const requestIds = result.matches.filter(m => m.type === 'RESOLVED_REQUEST').map(m => m.id);

    const [guides, requests, topicLabels, categoryLabels] = await Promise.all([
      guideIds.length
        ? this.database.guide.findMany({
            where: { id: { in: guideIds } },
            include: {
              author: { select: authorSelect },
              city: { select: { id: true, name: true, region: true } },
            },
          })
        : [],
      requestIds.length
        ? this.database.communityRequest.findMany({
            where: { id: { in: requestIds } },
            include: {
              author: { select: authorSelect },
              city: { select: { id: true, name: true, region: true } },
            },
          })
        : [],
      this.taxonomy.labels(TaxonomyKind.GUIDE_TOPIC),
      this.taxonomy.labels(TaxonomyKind.COMMUNITY_CATEGORY),
    ]);

    const guidesById = new Map(guides.map(row => [row.id, row] as const));
    const requestsById = new Map(requests.map(row => [row.id, row] as const));

    const matches = result.matches
      .map(candidate => {
        if (candidate.type === 'GUIDE') {
          const guide = guidesById.get(candidate.id);

          if (!guide) return null;

          return {
            type: 'GUIDE' as const,
            confidence: Number(candidate.confidence.toFixed(2)),
            guide: {
              id: guide.id,
              title: guide.title,
              topic: toTermView(guide.topicCode, topicLabels),
              intro: guide.intro,
              city: toCityView(guide.city),
              readTimeMinutes: guide.readTimeMinutes,
              counts: { views: guide.viewCount, likes: guide.likeCount },
              author: toAuthorView(guide.author, { sign: this.media.sign }),
              isAutoGenerated: guide.isAutoGenerated,
              publishedAt: guide.publishedAt?.toISOString() ?? null,
            },
          };
        }

        const request = requestsById.get(candidate.id);

        if (!request) return null;

        return {
          type: 'RESOLVED_REQUEST' as const,
          confidence: Number(candidate.confidence.toFixed(2)),
          request: {
            id: request.id,
            title: request.title,
            category: toTermView(request.categoryCode, categoryLabels),
            status: request.status,
            city: toCityView(request.city),
            counts: { helpers: request.helperCount, replies: request.replyCount },
            author: toAuthorView(request.author, { sign: this.media.sign, isAnonymous: request.visibility === 'ANONYMOUS',
            }),
            createdAt: request.createdAt.toISOString(),
          },
        };
      })
      .filter(Boolean);

    return { matches, similarAskCount: result.similarAskCount };
  }
}
