/* Shared helpers for the end-to-end scripts.
 *
 * The sweep matters: a script that crashes mid-run leaves its users behind, and
 * the next run then sees their data and fails an assertion that has nothing wrong
 * with it. Sweeping on the way IN rather than only on the way out makes each run
 * independent of how the last one ended. */
require('dotenv').config({ path: './.env' });
const jwt = require('jsonwebtoken');
const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const { Pool } = require('pg');

// Overridable so a sweep can run against a second instance while the usual one keeps port 4000.
const BASE = process.env.E2E_BASE_URL ?? 'http://localhost:4000/api/v1';
const E2E_PREFIX = 'e2e-';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

const state = { pass: 0, fail: 0 };

const check = (name, ok, detail) => {
  if (ok) {
    state.pass += 1;
    console.log(`  ✓ ${name}`);
  } else {
    state.fail += 1;
    console.log(
      `  ✗ ${name}${detail !== undefined ? ' — ' + JSON.stringify(detail).slice(0, 300) : ''}`,
    );
  }
};

async function api(token, method, path, body, extraHeaders = {}) {
  const res = await fetch(BASE + path, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...extraHeaders,
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await res.text();
  let json = null;

  try {
    json = text ? JSON.parse(text) : null;
  } catch {
    json = { raw: text };
  }

  return { status: res.status, body: json };
}

async function makeUser(tag, profile = {}) {
  const role = await prisma.role.findUnique({ where: { code: 'user' } });
  const stamp = Date.now() + Math.floor(Math.random() * 1000);
  const user = await prisma.user.create({
    data: {
      firstName: 'E2E',
      lastName: tag,
      email: `${E2E_PREFIX}${tag}-${stamp}@example.test`,
      username: `e2e_${tag}_${stamp}`,
      status: 'ACTIVE',
      userRole: { create: { roleId: role.id } },
      profile: { create: { cityId: 'MANCHESTER', ...profile } },
      trustChecks: { create: { check: 'EMAIL', status: 'VERIFIED', verifiedAt: new Date() } },
      sessions: {
        create: {
          userAgent: 'e2e',
          deviceType: 'cli',
          browserName: 'cli',
          operatingSystem: 'cli',
          ipAddress: '127.0.0.1',
          isActive: true,
          deviceFingerprint: `e2e-${tag}-${stamp}`,
        },
      },
    },
    include: { sessions: true },
  });

  return {
    id: user.id,
    token: jwt.sign({ sub: user.id, sid: user.sessions[0].id }, process.env.JWT_ACCESS_SECRET, {
      expiresIn: '1h',
    }),
  };
}

/** Removes every user any e2e script has ever created, and everything hanging off them. */
async function sweep(label = 'sweep') {
  const users = await prisma.user.findMany({
    where: { email: { startsWith: E2E_PREFIX } },
    select: { id: true },
  });

  const ids = users.map(user => user.id);

  if (ids.length) {
    await prisma.moderationQueueItem.deleteMany({ where: { subjectUserId: { in: ids } } });
    await prisma.report.deleteMany({
      where: { OR: [{ reporterId: { in: ids } }, { targetUserId: { in: ids } }] },
    });
    await prisma.activityEvent.deleteMany({ where: { userId: { in: ids } } });
    await prisma.idempotencyRecord.deleteMany({ where: { userId: { in: ids } } });
    await prisma.conversation.deleteMany({
      where: { participants: { some: { userId: { in: ids } } } },
    });
    await prisma.group.deleteMany({ where: { createdById: { in: ids } } });
    await prisma.user.deleteMany({ where: { id: { in: ids } } });
  }

  // Runs whether or not this sweep found users of its own, because a suite that deletes its own
  // members first leaves the orphans behind for somebody else to find. `guides.authorId` is
  // SetNull, since a Circl-drafted guide legitimately has no author, so a guide OUTLIVES the
  // member who wrote it. Right in production, where deletion anonymises and the row survives;
  // here it left every boundary-test guide sitting in the Guides tab forever.
  const orphaned = await prisma.guide.deleteMany({
    where: { authorId: null, isAutoGenerated: false },
  });

  // Same shape of leftover: deleting a user cascades their participant row away but leaves the
  // conversation, so a thread with nobody in it survives every sweep and accumulates.
  const emptyThreads = await prisma.conversation.deleteMany({
    where: { participants: { none: {} } },
  });

  // And again in the moderation queue, which holds ids rather than relations: sweeping the report
  // or the guide leaves the row behind. Ninety-two of them had built up, and since the queue pages
  // at fifty, a suite looking for the item it had just filed stopped finding it.
  const [reported, autoGuides] = await Promise.all([
    prisma.moderationQueueItem.findMany({
      where: { reportId: { not: null } },
      select: { id: true, reportId: true },
    }),
    prisma.moderationQueueItem.findMany({
      where: { targetType: 'GUIDE' },
      select: { id: true, targetId: true },
    }),
  ]);
  const [liveReports, liveGuides] = await Promise.all([
    prisma.report.findMany({
      where: { id: { in: reported.map(item => item.reportId) } },
      select: { id: true },
    }),
    prisma.guide.findMany({
      where: { id: { in: autoGuides.map(item => item.targetId) } },
      select: { id: true },
    }),
  ]);
  const liveReportIds = new Set(liveReports.map(row => row.id));
  const liveGuideIds = new Set(liveGuides.map(row => row.id));
  const staleQueue = await prisma.moderationQueueItem.deleteMany({
    where: {
      id: {
        in: [
          ...reported.filter(item => !liveReportIds.has(item.reportId)).map(item => item.id),
          ...autoGuides.filter(item => !liveGuideIds.has(item.targetId)).map(item => item.id),
        ],
      },
    },
  });

  if (!ids.length && !orphaned.count && !emptyThreads.count && !staleQueue.count) return 0;

  console.log(
    `  ${label}: removed ${ids.length} test users, their content` +
      `${orphaned.count ? ` and ${orphaned.count} authorless guides` : ''}` +
      `${emptyThreads.count ? ` and ${emptyThreads.count} empty threads` : ''}` +
      `${staleQueue.count ? ` and ${staleQueue.count} stale queue items` : ''}`,
  );

  return ids.length;
}

async function finish() {
  console.log(`\n═══ ${state.pass} passed, ${state.fail} failed ═══\n`);
  await prisma.$disconnect();
  await pool.end();
  process.exit(state.fail ? 1 : 0);
}

const fail = async error => {
  console.error(error);
  await prisma.$disconnect().catch(() => {});
  await pool.end().catch(() => {});
  process.exit(1);
};

const dobFor = years => {
  const date = new Date();

  date.setUTCFullYear(date.getUTCFullYear() - years);

  return date.toISOString().slice(0, 10);
};

/**
 * The seeded members sign in with an email code and no password (B.6). The route is throttled at
 * ten a minute keyed on the IP, and a whole sweep shares one IP, so a suite late in the run can be
 * refused for something no member would ever hit. Waits out the window the API itself names.
 */
async function verifyEmailCode(email, code = '1111', attempt = 0) {
  const res = await fetch(`${BASE}/auth/verify/email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, code }),
  });
  const body = await res.json().catch(() => ({}));

  if (res.status === 429 && attempt < 2) {
    const wait = (body?.data?.retryAfterSeconds ?? 30) + 1;

    console.log(`  … throttled signing in as ${email}, waiting ${wait}s`);
    await new Promise(resolve => setTimeout(resolve, wait * 1000));

    return verifyEmailCode(email, code, attempt + 1);
  }

  const cookies = res.headers.getSetCookie?.() ?? [];

  return {
    status: res.status,
    ok: res.status === 200 || res.status === 201,
    body: body?.data ?? {},
    cookieToken:
      cookies
        .find(c => c.startsWith('accessToken='))
        ?.split(';')[0]
        .split('=')[1] ?? null,
  };
}

/** A real PNG of the given size, so a header read on S3 has genuine bytes to find. */
function realPng(width, height) {
  const zlib = require('zlib');
  const chunk = (type, data) => {
    const len = Buffer.alloc(4);

    len.writeUInt32BE(data.length);

    const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
    const crc = Buffer.alloc(4);
    let c = ~0;

    for (const byte of body) {
      c ^= byte;
      for (let k = 0; k < 8; k += 1) c = (c >>> 1) ^ (0xedb88320 & -(c & 1));
    }

    crc.writeUInt32BE(~c >>> 0);

    return Buffer.concat([len, body, crc]);
  };
  const ihdr = Buffer.alloc(13);

  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 2;

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(Buffer.alloc(height * (1 + width * 3)))),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** Mints an upload slot, PUTs the bytes, and hands back the key an attach expects. */
async function uploadPng(token, purpose, width, height) {
  const bytes = realPng(width, height);
  const minted = await api(token, 'POST', '/media/uploads', {
    purpose,
    files: [{ mimeType: 'image/png', byteSize: bytes.length }],
  });
  const slot = minted.body?.data?.[0];

  if (!slot) return null;

  await fetch(slot.uploadUrl, {
    method: 'PUT',
    headers: { 'Content-Type': 'image/png' },
    body: bytes,
  });

  return slot.key;
}

module.exports = {
  api,
  check,
  dobFor,
  fail,
  finish,
  makeUser,
  prisma,
  realPng,
  sweep,
  uploadPng,
  verifyEmailCode,
};
